Merge 3.4-release into master
plotly/heroku-buildpack-python pull request #26
Opened 2020-02-21 22:12 UTC by joaoalf

Part of the unfreezing process.

@BRONSOLO I had to resolve a couple of conflicts on this one. Can you review please

2020-02-21 23:02 UTC, BRONSOLO requested changes
Thanks @joaoalf - the `/bin/steps/python` change looks good! Otherwise, the conflicts should be resolved by using what is on **master** imo.

2020-02-21 23:02 UTC, BRONSOLO commented on bin/steps/sqlite3
> +      echo "$SQLITE3_VERSION" > "$CACHE_DIR/.heroku/python-sqlite3-version"
I would think we would also want to use what is on **master** here as well. This pin was fixed in: https://github.com/heroku/heroku-buildpack-python/commit/ffc7683c05c924d345b43c6ad1c5ea8b4a5a5fb1

2020-02-21 23:02 UTC, BRONSOLO commented on README.md
> +- Create a PR, get it approved, and merge.
We should be using what is on **master** here (new release steps introduced here:https://github.com/plotly/heroku-buildpack-python/commit/1b008b36155e32aceb435b25f88beb6903d36a37)

2020-02-24 22:45 UTC, joaoalf commented
@BRONSOLO Updated. Can you please check again?

2020-02-25 19:41 UTC, BRONSOLO commented
:dancer: Thanks for the changes - looks good to me @joaoalf.

2020-02-25 20:53 UTC, merged